name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18
      id: go

    - name: Check out code
      uses: actions/checkout@v2 


    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: |
        cd cmd
        go build -v -o StockAppBinary
        cd ..

    - name: Copy binary to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        source: "cmd/StockAppBinary"
        target: "/home/ubuntu/StockApp/cmd/StockAppBinary"

    - name: Copy template file to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        source: "pkg/template/table.tmpl"
        target: "/home/ubuntu/StockApp/pkg/template/table.tmpl"

    - name: Create .env file on EC2
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          script: "echo ${{ secrets.BACKEND_VARS }} >> /home/ubuntu/StockApp/cmd/.env"
    
    - name: Run app on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: "sudo chmod +x /home/ubuntu/StockApp/cmd/StockAppBinary && sudo chmod 777 /home/ubuntu/StockApp/cmd/StockAppBinary && sudo nohup /home/ubuntu/StockApp/cmd/StockAppBinary > app.log 2>&1 &"
